apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: claim-log-1
  containers:
  - name: webapp
    image: "kodekloud/event-simulator"
    volumeMounts:
    - name: vol
      mountPath: /log
