apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  volumes:
  - name: vol
    hostPath:
      path: /var/log/webapp
  containers:
  - name: webapp
    image: "kodekloud/event-simulator"
    volumeMounts:
    - name: vol
      mountPath: /log
