apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  hostPath:
    path: "/pv/log"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
